# Generated by Django 5.2.3 on 2025-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ziplink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
