# Generated by Django 5.2.3 on 2025-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ziplink', '0003_alter_link_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='sl_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
